DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE AUTHORS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    BIRTH_DATE DATE,
    BIOGRAPHY VARCHAR(500),
    NATIONALITY VARCHAR(50)
);

CREATE TABLE BOOKS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    PUBLICATION_DATE DATE NOT NULL,
    ISBN VARCHAR(17) NOT NULL,
    PAGE_COUNT INT,
    AUTHOR_ID BIGINT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID)
);

CREATE INDEX IDX_BOOKS_AUTHOR ON BOOKS(AUTHOR_ID);
CREATE INDEX IDX_BOOKS_TITLE ON BOOKS(TITLE);
CREATE INDEX IDX_AUTHORS_NAME ON AUTHORS(NAME);